DO BEGIN
DECLARE V_COUNTER INTEGER;
DECLARE i INTEGER DEFAULT 1;
DECLARE V_DATE DATE;
T =
SELECT ROW_NUMBER() OVER() R_NUM,
    *
FROM(
        SELECT DISTINCT CAST("SNAPSHOT_ID" AS DATE) SNAPSHOT_DATE
        FROM "E199551"."V_HOST_SQL_PLAN_CACHE"
    );
SELECT *
FROM :T;
V_COUNTER :=::ROWCOUNT;
FOR i IN 1..V_COUNTER DO
SELECT SNAPSHOT_DATE INTO V_DATE
FROM :T
WHERE R_NUM = :i;
INSERT INTO YKTM_EXE_STATS
SELECT CAST("SNAPSHOT_ID" AS DATE),
    STATEMENT_HASH,
    A.USER_NAME,
    SESSION_USER_NAME,
    VALUE,
    EXECUTION_COUNT,
    APPLICATION_NAME,
    "STATEMENT_STRING",
    "ACCESSED_OBJECT_NAMES",
    "ACCESSED_TABLE_NAMES"
FROM "E199551"."V_HOST_SQL_PLAN_CACHE" A
    LEFT JOIN "SYS"."USER_PARAMETERS" C ON C."USER_NAME" = A.USER_NAME
    AND PARAMETER = 'EMAIL ADDRESS'
WHERE CAST("SNAPSHOT_ID" AS DATE) = V_DATE;
COMMIT;
end for;
END