SELECT PACKAGE_ID,
    OBJECT_NAME,
    OBJECT_SUFFIX,
    DELIVERY_UNIT,
    VERSION_ID,
    ACTIVATED_AT,
    ACTIVATED_BY,
    EDIT,
    OBJECT_STATUS
FROM _SYS_REPO.ACTIVE_OBJECT
WHERE PACKAGE_ID LIKE 'MHK_FNA%'
    AND PACKAGE_ID not LIKE '%TMS%' --AND OBJECT_SUFFIX LIKE '%view%'
ORDER BY OBJECT_SUFFIX,
    1,
    2
SELECT PACKAGE_ID,
    DELIVERY_UNIT
FROM _SYS_REPO.PACKAGE_CATALOG
WHERE PACKAGE_ID LIKE 'MHK_FNA%'
ORDER BY 2
SELECT OBJECT_NAME
FROM _SYS_REPO.ACTIVE_OBJECT
WHERE PACKAGE_ID LIKE 'MHK_FNA%'
    AND PACKAGE_ID not LIKE '%TMS%'
    AND OBJECT_SUFFIX LIKE '%view%'