DO BEGIN A =
SELECT "WERKS",
    1 AS "KONTS",
    "GJPER",
    "MATBF",
    --TXT50,
    SUM("DMBTR_STOCK") AS "DMBTR_STOCK"
FROM "_SYS_BIC"."Work.inventory.POC.RF/MATDOC_ACCOUNT"
WHERE (
        "WERKS" = '6221'
        AND "KONTS" IN ('0001250530', '0001250520') --AND MATBF = '80526.689.1200.A'
        AND "GJPER" = '2023006'
    )
GROUP BY "WERKS",
    --TXT50,
    "KONTS",
    "GJPER",
    "MATBF";
B =
SELECT "BWKEY",
    "FISCYEARPER",
    1 AS "RACCT",
    "MATNR",
    SUM("HSL") AS "HSL"
FROM "QS5_TO_AIQ"."ACDOCA"
WHERE "BWKEY" = '6221'
    AND RACCT IN ('0001250530', '0001250520') --AND MATNR = '80526.689.1200.A'
    AND "FISCYEARPER" = '2023006'
GROUP BY "BWKEY",
    "FISCYEARPER",
    "RACCT",
    "MATNR";
SELECT COUNT(*)
FROM :A;
SELECT COUNT(*)
FROM :B;
C =
SELECT A.*,
    B.HSL,
    RACCT
FROM :A A
    LEFT JOIN :B B ON A.MATBF = B.MATNR
    AND WERKS = BWKEY
    AND KONTS = RACCT;
SELECT DISTINCT *
FROM :C --WHERE DMBTR_STOCK <> COALESCE(HSL,0)
;
END