DO BEGIN
DECLARE V_LAST_FISCAL_MONTH_END_DATE DATE;
DECLARE V_FISCAL_MONTH NVARCHAR(7);
SELECT YEAR(ADD_MONTHS("DATE_SQL", -1 * 1)) || LPAD(MONTH(ADD_MONTHS("DATE_SQL", -1 * 1)), 3, '0') INTO V_FISCAL_MONTH
FROM (
        SELECT CAST(FISCYEAR_MONTH || '01' AS DATE) AS DATE_SQL
        FROM "_SYS_BIC"."MHK_FNA.Base.MasterData/MHK_BVDM_MD_BUSINESS_UNIT_DATE"
        WHERE "DATE_SQL" = CURRENT_DATE
    );
SELECT DISTINCT "LAST_DATE_OF_FISCPER"
FROM "_SYS_BIC"."MHK_FNA.Base.MasterData/MHK_BVDM_MD_BUSINESS_UNIT_DATE"
WHERE "FISCYEAR_PERIOD" = :V_FISCAL_MONTH;
END