SELECT A."VBELN",
    -- "POSNR",
    A."MATNR",
    A.WERKS,
    MATWA,
    "SELLING_PKG_SKU",
    D.MATNR,
    "PSTYV",
    "AUART_ANA",
    SUM("KWMENG") AS "KWMENG_SUM",
    B.MTART,
    B.MTBEZ,
    SUM(TOTAL_INV_QUAN)
FROM "QS5_TO_AIQ"."VBAP" A
    INNER JOIN "QS5_TO_AIQ"."VBAK" X ON A.VBELN = X.VBELN
    left join "_SYS_BIC"."MHK_FNA.Reuse.MasterData/MHK_RVDM_MD_MATERIAL" B -- "QS5_TO_AIQ".MARA B
    ON A.MATNR = B.MATNR
    LEFT JOIN "_SYS_BIC"."Work.inventory.POC/DEL_MHK_IM_BOM" C ON A.MATWA = "SELLING_COMP_SKU"
    LEFT JOIN "QS5_TO_AIQ".MAST D ON A.MATWA = D.MATNR
    LEFT JOIN "_SYS_BIC"."MHK_FNA.Reporting.Inventory/MHK_INV_CURRENT_INVENTORY"(
        'PLACEHOLDER' = ('$$IP_CPUDT$$', '20221101'),
        'PLACEHOLDER' = ('$$IP_UOM$$', 'LFT')
    ) Y ON A.MATNR = Y.MATNR
    AND A.WERKS = Y.WERKS
WHERE "AUART_ANA" = 'ZOR7'
    AND VBTYP = 'C'
GROUP BY A."VBELN",
    --"POSNR",
    A."MATNR",
    A.WERKS,
    MATWA,
    "PSTYV",
    "AUART_ANA",
    B.MTART,
    B.MTBEZ,
    "SELLING_PKG_SKU",
    D.MATNR
ORDER BY A."VBELN" ASC,
    --"POSNR" ASC,
    A."MATNR" ASC,
    "PSTYV" ASC,
    "AUART_ANA" ASC;