SELECT DISTINCT "MAABC" SKU_RANK,
    A."MMSTA",
    MTSTB SKU_RANK_DESC,
    A."WERKS",
    NAME1 PLANT_NAME,
    B.BUKRS,
    BUTXT COMP_DESC
FROM "QS5_TO_AIQ"."MARC" A
    LEFT JOIN "QS5_TO_AIQ".T001K B ON WERKS = BWKEY
    LEFT JOIN "QS5_TO_AIQ".T141T C ON A.MMSTA = C.MMSTA
    AND SPRAS = 'E'
    LEFT JOIN "QS5_TO_AIQ".T001 D ON B.BUKRS = D.BUKRS
    LEFT JOIN "QS5_TO_AIQ".T001W E ON A.WERKS = E.WERKS --WHERE (A."MMSTA" <> '' AND "MAABC" <> '')
ORDER BY B.BUKRS DESC