DO BEGIN
DECLARE P_VIEW_NAME NVARCHAR(300) DEFAULT 'MHK_FNA.Reuse.Inventory/MHK_RVCU_IM_INV_SNAPSHOT';
--P_VIEW_NAME := 'MHK_FNA.Reporting.Inventory/MHK_INV_CURRENT_INVENTORY';
--P_VIEW_NAME := 'MHK_FNA.Reuse.Inventory/MHK_RVCU_IM_CURRENT_INVENTORY';
P_VIEW_NAME := 'MHK_FNA.Reporting.Inventory/MHK_INV_SNAPSHOT';
T_BATCH_MATRL =
SELECT "VIEW_NAME",
    "COLUMN_NAME",
    'BATCH_ATTR' AS FIELD_TYPE
FROM "_SYS_BIC"."Work.inventory/UTL_VIEW_COLUMNS"
WHERE "VIEW_NAME" IN (
        'MHK_FNA.Reuse.Inventory/MHK_RVDM_IM_BATCH_ATTRIBUTES'
    )
UNION
SELECT "VIEW_NAME",
    "COLUMN_NAME",
    'MATRL_ATTR' AS TYPE
FROM "_SYS_BIC"."Work.inventory/UTL_VIEW_COLUMNS"
WHERE "VIEW_NAME" IN (
        'MHK_FNA.Reuse.MasterData/MHK_RVDM_MD_T_MATERIAL_ATTR'
    );
SELECT *
FROM :T_BATCH_MATRL;
T_DTL =
SELECT BASE_OBJECT_NAME,
    FIELDNAME
FROM OBJECT_DEPENDENCIES
    INNER JOIN "_SYS_BIC"."Work.inventory/DCV_TABLE_DETAILS_PE2" ON "TABNAME" = BASE_OBJECT_NAME
WHERE DEPENDENT_OBJECT_NAME = :P_VIEW_NAME
    AND BASE_OBJECT_TYPE = 'TABLE';
T_FL =
SELECT POSITION,
    A."VIEW_NAME",
    A."COLUMN_NAME",
    COMMENTS,
    BASE_OBJECT_NAME AS SAP_TABLE_NAME,
    FIELDNAME AS SAP_FIELD_NAME,
    FIELD_TYPE,
    '' AS CALC
FROM "_SYS_BIC"."Work.inventory/UTL_VIEW_COLUMNS" A
    LEFT JOIN :T_BATCH_MATRL B ON A."COLUMN_NAME" = B."COLUMN_NAME"
    LEFT JOIN :T_DTL ON A.COLUMN_NAME = FIELDNAME
WHERE A."VIEW_NAME" = :P_VIEW_NAME
    AND A."COLUMN_NAME" <> 'MANDT';
SELECT *
FROM :T_FL
ORDER BY 1;
SELECT *
FROM :T_FL
WHERE SAP_TABLE_NAME IS NULL
    AND FIELD_TYPE IS NULL
ORDER BY 1;
END