do (
    IN P_LOAD_INITIAL_FLAG NVARCHAR(1) => 'N',
    IN P_DAYS INTEGER => -1
) BEGIN
DECLARE V_UPDATED_TIMESTAMP TIMESTAMP;
DECLARE V_PREVIOUS_RUN_DATE DATE;
DECLARE V_ROW_COUNT INTEGER;
DECLARE V_PRV_RUN_CHK INTEGER;
DECLARE V_UPDATE_ROW_COUNT INTEGER;
DECLARE V_INSERT_ROW_COUNT INTEGER;
DECLARE V_MAX_TIMESTAMP TIMESTAMP;
DECLARE EX_MESSAGE NVARCHAR(2000);
DECLARE V_CREST_START_DATE NVARCHAR(8);
-- 06/07/2023 
/* Error Message */
--T_LOG
DECLARE LV_EXE_DATE NVARCHAR(8);
DECLARE LV_EXE_TIME NVARCHAR(8);
DECLARE LV_REC_CNT INTEGER;
--T_LOG
/*Exit Handler for Job*/
--DECLARE V_TIDAL CONDITION FOR SQL_ERROR_CODE 10001; /*Alert Tidal with failed job exception*/
/*
 DECLARE EXIT HANDLER FOR SQLEXCEPTION
 BEGIN
 
 EX_MESSAGE := 'SQL Exception occured. Error Code is: ' || ::SQL_ERROR_CODE || ' Error message is: ' || ::SQL_ERROR_MESSAGE;
 
 INSERT 
 INTO "MHK_EDW_MART"."MHK_FNA.Base.CrossFunc::T_JOB_LOG" SELECT
 :LV_EXE_DATE,
 :LV_EXE_TIME,
 SESSION_USER,
 ::CURRENT_OBJECT_NAME,
 1,
 TO_NVARCHAR(CURRENT_TIMESTAMP,
 'YYYY-MM-DD HH24:MI:SS') || ' Initial Load - '|| V_ROW_COUNT||','||V_UPDATE_ROW_COUNT||','||V_INSERT_ROW_COUNT 
 
 FROM DUMMY;
 COMMIT;
 
 
 SIGNAL V_TIDAL SET MESSAGE_TEXT = :EX_MESSAGE;
 
 
 END;
 
 */
/*End Exit Handler for Job*/
T_BWKEY =
SELECT DISTINCT BWKEY
FROM "_SYS_BIC"."MHK_FNA.Base.MasterData/MHK_BVDM_MD_T001" A
    INNER JOIN "_SYS_BIC"."MHK_FNA.Base.MasterData/MHK_BVDM_MD_T001K" B ON A.BUKRS = B.BUKRS
WHERE "WAERS" = 'USD'
    AND A.BUKRS LIKE '8%';
SELECT TO_CHAR(CURRENT_DATE, 'YYYYMMDD'),
    TO_CHAR(CURRENT_TIME, 'HH24MISS') INTO LV_EXE_DATE,
    LV_EXE_TIME
FROM DUMMY;
SELECT CAST(MAX(UPDATED_TIMESTAMP) AS DATE) INTO V_PREVIOUS_RUN_DATE
FROM "E199551"."KTM_T_MATERIAL_PLANT_ATTR_TYPE2";
-- Initial Load
IF P_LOAD_INITIAL_FLAG = 'Y' THEN TRUNCATE TABLE "E199551"."KTM_T_MATERIAL_PLANT_ATTR_TYPE2";
COMMIT;
--Begin Change 06/07/2023 
SELECT "LOW" INTO V_CREST_START_DATE
FROM "MHK_EDW_MART"."MHK_FNA.Base.MasterData::T_HANA_TVARVC"
WHERE "NAME" = 'P_CREST_START_DATE';
--End Change 06/07/2023 
--Get required Type 2 Fields from MARA/MARC
--Any new Type 2 fields need to be added here and also in Unpivot section
T_MARA =
SELECT CAST(V_CREST_START_DATE AS DATE) AS "START_DATE",
    '9999-12-31' AS END_DATE,
    T1."MATNR",
    "WERKS",
    "MAABC",
    --CAST(T2."STPRS" AS NVARCHAR(30)) AS "STPRS",
    CAST(T2."UNIT_PRICE" AS NVARCHAR(30)) AS "UNIT_PRICE"
FROM "_SYS_BIC"."MHK_FNA.Base.MasterData/MHK_BVDM_MD_MARC" T1
    LEFT JOIN (
        SELECT DISTINCT "MATNR",
            "BWKEY",
            "STPRS",
            "STPRS" / "PEINH" AS "UNIT_PRICE"
        FROM "_SYS_BIC"."MHK_FNA.Base.Inventory/MHK_BVCU_IM_MBEW"
        WHERE BWKEY IN (
                SELECT DISTINCT BWKEY
                FROM :T_BWKEY
            )
    ) T2 ON T1."MATNR" = T2."MATNR"
    AND T1."WERKS" = T2."BWKEY";
SELECT *
FROM :T_MARA;
--Unpivot MARA 
T_UNPIVOT_MARA =
SELECT START_DATE,
    END_DATE,
    MATNR,
    WERKS,
    'MAABC' as FIELD,
    COALESCE(MAABC, '') AS "VALUE"
FROM :T_MARA
UNION
--SELECT START_DATE,END_DATE,MATNR,WERKS,'STPRS' as "FIELD",COALESCE("STPRS",'0') AS "VALUE"  FROM :T_MARA UNION
SELECT START_DATE,
    END_DATE,
    MATNR,
    WERKS,
    'UNIT_PRICE' as "FIELD",
    COALESCE("UNIT_PRICE", '0') AS "VALUE"
FROM :T_MARA;
INSERT INTO "E199551"."KTM_T_MATERIAL_PLANT_ATTR_TYPE2"
SELECT START_DATE,
    END_DATE,
    MATNR,
    WERKS,
    FIELD,
    "VALUE",
    CURRENT_TIMESTAMP AS UPDATED_TIMESTAMP
FROM :T_UNPIVOT_MARA;
V_ROW_COUNT :=::ROWCOUNT;
/*
 INSERT INTO  "MHK_EDW_MART"."MHK_FNA.Base.CrossFunc::T_JOB_LOG" SELECT
 
 
 
 :LV_EXE_DATE,
 :LV_EXE_TIME,
 SESSION_USER,
 ::CURRENT_OBJECT_NAME,
 
 1,
 TO_NVARCHAR(CURRENT_TIMESTAMP,'YYYY-MM-DD HH24:MI:SS') || ' Initial Load - '|| V_ROW_COUNT FROM DUMMY;
 
 COMMIT;
 */
-- Delta Load
ELSE
/*
 SELECT COUNT(*) INTO V_PRV_RUN_CHK FROM "MHK_EDW_MART"."MHK_FNA.Base.CrossFunc::T_JOB_LOG" WHERE EXE_DATE = CURRENT_DATE 
 AND JOB_PROCEDURE_NAME = ::CURRENT_OBJECT_NAME;
 
 */
--IF :V_PRV_RUN_CHK = 0 AND V_PREVIOUS_RUN_DATE < CURRENT_DATE THEN 
IF V_PREVIOUS_RUN_DATE < CURRENT_DATE THEN
SELECT MAX(UPDATED_TIMESTAMP) INTO V_MAX_TIMESTAMP
FROM "E199551"."KTM_T_MATERIAL_PLANT_ATTR_TYPE2";
T_MARA_DELTA =
SELECT CAST(CURRENT_DATE AS DATE) AS "START_DATE",
    '9999-12-31' AS END_DATE,
    T1."MATNR",
    "WERKS",
    "MAABC",
    --CAST(T2."STPRS" AS NVARCHAR(30)) AS "STPRS",
    CAST(T2."UNIT_PRICE" AS NVARCHAR(30)) AS "UNIT_PRICE"
FROM "_SYS_BIC"."MHK_FNA.Base.MasterData/MHK_BVDM_MD_MARC" T1
    LEFT JOIN (
        SELECT DISTINCT "MATNR",
            "BWKEY",
            "STPRS",
            "STPRS" / "PEINH" AS "UNIT_PRICE"
        FROM "_SYS_BIC"."MHK_FNA.Base.Inventory/MHK_BVCU_IM_MBEW"
        WHERE CAST("LAEPR" AS DATE) > CAST (:V_MAX_TIMESTAMP AS DATE)
            AND BWKEY IN (
                SELECT DISTINCT BWKEY
                FROM :T_BWKEY
            )
    ) T2 ON T1."MATNR" = T2."MATNR"
    AND T1."WERKS" = T2."BWKEY"
    INNER JOIN "_SYS_BIC"."MHK_FNA.Base.MasterData/MHK_BVDM_MD_MARA" T3 ON T1.MATNR = T3.MATNR
WHERE CAST("LAEDA" AS DATE) > CAST (:V_MAX_TIMESTAMP AS DATE);
T_UNPIVOT_MARA_DELTA =
SELECT START_DATE,
    END_DATE,
    MATNR,
    WERKS,
    'MAABC' as FIELD,
    COALESCE(MAABC, '') AS "VALUE"
FROM :T_MARA_DELTA
UNION
--SELECT START_DATE,END_DATE,MATNR,WERKS,'STPRS' as "FIELD",COALESCE("STPRS",'0') AS "VALUE"  FROM :T_MARA_DELTA UNION
SELECT START_DATE,
    END_DATE,
    MATNR,
    WERKS,
    'UNIT_PRICE' as "FIELD",
    COALESCE("UNIT_PRICE", '0') AS "VALUE"
FROM :T_MARA_DELTA;
V_ROW_COUNT :=::ROWCOUNT;
-- total delta rows
SELECT CURRENT_TIMESTAMP INTO V_UPDATED_TIMESTAMP
FROM DUMMY;
-- Update dimension if value changes , 
MERGE INTO "E199551"."KTM_T_MATERIAL_PLANT_ATTR_TYPE2" T1 USING :T_UNPIVOT_MARA_DELTA T2 ON T1."MATNR" = T2."MATNR"
AND T1."FIELD" = T2."FIELD"
AND T1."WERKS" = T2."WERKS"
WHEN MATCHED
AND COALESCE(T1."VALUE", '') <> COALESCE(T2."VALUE", '')
AND T1."END_DATE" = '9999-12-31' THEN
UPDATE
SET T1."END_DATE" = ADD_DAYS(T2."START_DATE", -1),
    T1.UPDATED_TIMESTAMP = :V_UPDATED_TIMESTAMP;
V_UPDATE_ROW_COUNT :=::ROWCOUNT;
-- rows updated
-- Add new entries
MERGE INTO "E199551"."KTM_T_MATERIAL_PLANT_ATTR_TYPE2" T1 USING :T_UNPIVOT_MARA_DELTA T2 ON T1."END_DATE" = T2."END_DATE"
AND T1."MATNR" = T2."MATNR"
AND T1."FIELD" = T2."FIELD"
AND T1."WERKS" = T2."WERKS"
AND COALESCE(T1."VALUE", '') = COALESCE(T2."VALUE", '')
WHEN NOT MATCHED THEN
INSERT
VALUES (
        T2."START_DATE",
        T2."END_DATE",
        T2."MATNR",
        T2."WERKS",
        T2."FIELD",
        T2."VALUE",
        :V_UPDATED_TIMESTAMP
    );
V_INSERT_ROW_COUNT :=::ROWCOUNT;
--rows inserted
/*
 INSERT 
 INTO "MHK_EDW_MART"."MHK_FNA.Base.CrossFunc::T_JOB_LOG" SELECT
 :LV_EXE_DATE,
 :LV_EXE_TIME,
 SESSION_USER,
 ::CURRENT_OBJECT_NAME,
 1,
 TO_NVARCHAR(CURRENT_TIMESTAMP,
 'YYYY-MM-DD HH24:MI:SS') || ' Delta Load - '|| V_ROW_COUNT||','||V_UPDATE_ROW_COUNT||','||V_INSERT_ROW_COUNT 
 FROM DUMMY
 ;
 COMMIT
 ;
 */
ELSE
/*
 -- prevent job from running more than once a day
 
 UPDATE "MHK_EDW_MART"."MHK_FNA.Base.CrossFunc::T_JOB_LOG" 
 
 SET MESSAGE = (SELECT DISTINCT MESSAGE||', '||CURRENT_TIMESTAMP ||' Job Already Run Today'  FROM "MHK_EDW_MART"."MHK_FNA.Base.CrossFunc::T_JOB_LOG"
 
 WHERE EXE_DATE = CURRENT_DATE AND JOB_PROCEDURE_NAME = ::CURRENT_OBJECT_NAME LIMIT 1 )
 
 WHERE EXE_DATE = CURRENT_DATE AND JOB_PROCEDURE_NAME = ::CURRENT_OBJECT_NAME;
 
 COMMIT;
 */
END IF;
END IF;
END