SELECT "CC_FISCAL_YEAR_MONTH",
    "FISCAL_YEAR",
    "SNAPSHOT_DATE",
    SUM("CAMS_AVAILABLE_LENGTH_IN_SQ_YDS"),
    SUM("S4_CC_INVENTORY_VALUE"),
    SUM("S4_CC_AVAILABLE_QTY"),
    SUM("CAMS_FG_INVENTORY_VALUE_AMT")
FROM "_SYS_BIC"."Work.inventory.POC.RECON/MHK_INV_SOFTSURF_SNPSHT_V1"(
        'PLACEHOLDER' = ('$$IP_FROM_DATE$$', '2023-10-01'),
        'PLACEHOLDER' = ('$$IP_UOM$$', 'LFT')
    )
WHERE (
        "CC_FINISHED_ROLL_NUM_COMPARISON" = 'TRUE'
        AND CC_TOT_INV_QTY_COMPARISON = 'TRUE'
    )
GROUP BY "CC_FISCAL_YEAR_MONTH",
    "FISCAL_YEAR",
    "SNAPSHOT_DATE"