DO BEGIN T_MAT =
SELECT --"WERKS",--"ZF_ORIG_LENGTH_IN",
    DISTINCT DIVISION AS DIV,
    VTWEG,
    VKORG VKRG,
    A."MATNR",
    "STYLE_CD",
    "SIZE_CD",
    "COLOR_CD",
    "BACKING_CD",
    "ZF_QUALITY_CODE",
    "MSTAE",
    "ZF_BALANCE_WIDTH_IN",
    "WIDTH",
    "LENGTH"
FROM "_SYS_BIC"."MHK_FNA.Reporting.Inventory/MHK_INV_CURRENT_INVENTORY"(
        'PLACEHOLDER' = ('$$IP_CPUDT$$', '20230604'),
        'PLACEHOLDER' = ('$$IP_UOM$$', 'LFT')
    ) A
    LEFT JOIN QS5_TO_AIQ.MVKE B ON A.MATNR = B.MATNR
WHERE ("STYLE_CD" = '28028')
    AND A.MATNR = '28028.711.1200.H4';
SELECT *
FROM :T_MAT;
--ZSIS
--ALL
T_SQ1 =
SELECT "MATNR",
    "STYLE_CD",
    "SIZE_CD",
    "COLOR_CD",
    "BACKING_CD",
    "ZF_QUALITY_CODE",
    "MSTAE",
    "ZF_BALANCE_WIDTH_IN",
    "WIDTH",
    "LENGTH",
    "KNUMH"
FROM :T_MAT
    LEFT JOIN QS5_TO_AIQ.A9HR ON "STYLE_CD" = "ZKWAL"
    AND "SIZE_CD" = "ZZSIZE"
    AND "COLOR_CD" = "ZKLR"
    AND "BACKING_CD" = "ZBACK"
WHERE "KSCHL" = 'ZSIS'
    AND VKORG = '8135'
    AND SPART = '81'
    AND CURRENT_DATE BETWEEN DATBI AND DATAB;
--ZSIS
-- NO COLOR
T_SQ2_MAT =
SELECT DISTINCT MATNR
FROM :T_MAT
EXCEPT
SELECT DISTINCT MATNR
FROM :T_SQ1;
SELECT *
FROM :T_SQ2_MAT;
select *
from QS5_TO_AIQ.A9PF
where "ZKWAL" = '28028';
T_SQ2 =
SELECT "MATNR",
    "STYLE_CD",
    "SIZE_CD",
    "COLOR_CD",
    "BACKING_CD",
    "ZF_QUALITY_CODE",
    "MSTAE",
    "ZF_BALANCE_WIDTH_IN",
    "WIDTH",
    "LENGTH",
    "KNUMH"
FROM :T_MAT
    LEFT JOIN QS5_TO_AIQ.A9PF ON "STYLE_CD" = "ZKWAL"
    AND "SIZE_CD" = "ZZSIZE"
    AND "BACKING_CD" = "ZBACK"
    AND VKORG = '8135'
    AND SPART = '81'
WHERE MATNR IN (
        SELECT DISTINCT MATNR
        FROM :T_SQ2_MAT
    ) --AND "KSCHL" = 'ZSIS'
    AND CURRENT_DATE BETWEEN DATAB AND DATBI;
SELECT *
FROM :T_SQ2;
--ZSIS
-- NO BACK
T_SQ3_MAT =
SELECT DISTINCT MATNR
FROM :T_MAT
EXCEPT
SELECT DISTINCT MATNR
FROM :T_SQ2
UNION
SELECT DISTINCT MATNR
FROM :T_SQ1;
T_SQ3 =
SELECT "MATNR",
    "STYLE_CD",
    "SIZE_CD",
    "COLOR_CD",
    "BACKING_CD",
    "ZF_QUALITY_CODE",
    "MSTAE",
    "ZF_BALANCE_WIDTH_IN",
    "WIDTH",
    "LENGTH",
    "KNUMH"
FROM :T_MAT
    LEFT JOIN QS5_TO_AIQ.A9HS ON "STYLE_CD" = "ZKWAL"
    AND "SIZE_CD" = "ZZSIZE"
WHERE MATNR IN (
        SELECT MATNR
        FROM :T_SQ3_MAT
    ) --AND "KSCHL" = 'ZSIS'
    AND VKORG = '8135'
    AND SPART = '81'
    AND CURRENT_DATE BETWEEN DATBI AND DATAB;
SELECT *
FROM :T_SQ3;
END