--PRODUCT_TYPE_CD
SELECT TOP 200 DISTINCT "PRODUCT_TYPE_CD",
    "PRODUCT_TYPE_DESC"
FROM "_SYS_BIC"."mhk.edw_mart.hana_views/MHK_ATVW_SOFT_SURF_PRODUCT_AND_CAT"
ORDER BY "PRODUCT_TYPE_CD" ASC,
    "PRODUCT_TYPE_DESC" ASC;
--
Generated SQL:
SELECT TOP 200 DISTINCT "PRODUCT_OWNER_CD",
    "PRODUCT_OWNER_DESC"
FROM "_SYS_BIC"."mhk.edw_mart.hana_views/MHK_ATVW_SOFT_SURF_PRODUCT_AND_CAT"
ORDER BY "PRODUCT_OWNER_CD" ASC,
    "PRODUCT_OWNER_DESC" ASC;
Generated SQL:
SELECT TOP 200 DISTINCT "QUALITY_CD",
    "QUALITY_DESC"
FROM "MHK_EDW_MART"."DIM_QUALITY"
ORDER BY "QUALITY_CD" ASC,
    "QUALITY_DESC" ASC;
Generated SQL:
SELECT TOP 5000 DISTINCT "PROCESS_CD",
    "PROCESS_DESC"
FROM "MHK_EDW_MART"."DIM_MFG_PROCESS_TYPE"
ORDER BY "PROCESS_CD" ASC,
    "PROCESS_DESC" ASC;
Generated SQL:
SELECT TOP 200 DISTINCT "FLOORING_TYPE_CODE",
    "FLOORING_TYPE_DESCRIPTION"
FROM "_SYS_BIC"."mhk.edw_mart.hana_views/MHK_CEVW_INVENTORY_SNAPSHOTS_G/dp/Join_3"
ORDER BY "FLOORING_TYPE_CODE" ASC,
    "FLOORING_TYPE_DESCRIPTION" ASC;
Generated SQL:
SELECT TOP 200 DISTINCT "FLOORING_CATEGORY_DESCRIPTION",
    "FLOORING_CATEGORY_CODE"
FROM "_SYS_BIC"."mhk.edw_mart.hana_views/MHK_CEVW_INVENTORY_SNAPSHOTS_G/dp/Join_3"
ORDER BY "FLOORING_CATEGORY_DESCRIPTION" ASC,
    "FLOORING_CATEGORY_CODE" ASC;
Generated SQL:
SELECT TOP 200 DISTINCT "FLOORING_CATEGORY_GROUP_DESCRIPTION",
    "FLOORING_CATEGORY_GROUP_CODE"
FROM "_SYS_BIC"."mhk.edw_mart.hana_views/MHK_CEVW_INVENTORY_SNAPSHOTS_G/dp/Join_3"
ORDER BY "FLOORING_CATEGORY_GROUP_DESCRIPTION" ASC,
    "FLOORING_CATEGORY_GROUP_CODE" ASC;
Generated SQL:
SELECT TOP 200 DISTINCT "PRODUCT_TYPE_DESCRIPTION",
    "PRODUCT_TYPE_CODE"
FROM "_SYS_BIC"."mhk.edw_mart.hana_views/MHK_CEVW_INVENTORY_SNAPSHOTS_G/dp/Join_3"
ORDER BY "PRODUCT_TYPE_DESCRIPTION" ASC,
    "PRODUCT_TYPE_CODE" ASC;