SELECT "APPLICATION_NAME",
    AVG("AVG_EXECUTION_MEMORY_SIZE_GB"),
    MAX("AVG_EXECUTION_MEMORY_SIZE_GB"),
    AVG(AVG_EXECUTION_TIME_SEC),
    MAX(AVG_EXECUTION_TIME_SEC),
    COUNT(*)
FROM (
        SELECT "USER_NAME",
            SESSION_USER_NAME,
            "STATEMENT_HASH" STMT_HASH,
            TO_VARCHAR(STATEMENT_STRING),
            CAST("SNAPSHOT_ID" AS DATE) SNAP_DATE,
            "APPLICATION_NAME",
            -- "APPLICATION_SOURCE",
            CAST(
                "AVG_EXECUTION_MEMORY_SIZE" /(1024 * 1024) AS DECIMAL(13, 3)
            ) AS "AVG_EXECUTION_MEMORY_SIZE_MB",
            CAST(
                "AVG_EXECUTION_MEMORY_SIZE" /(1024 * 1024 * 1024) AS DECIMAL(13, 3)
            ) AS "AVG_EXECUTION_MEMORY_SIZE_GB",
            CAST(
                "MAX_EXECUTION_MEMORY_SIZE" /(1024 * 1024) AS DECIMAL(13, 3)
            ) AS "MAX_EXECUTION_MEMORY_SIZE_MB",
            CAST(
                "MAX_EXECUTION_MEMORY_SIZE" /(1024 * 1024 * 1024) AS DECIMAL(13, 3)
            ) AS "MAX_EXECUTION_MEMORY_SIZE_GB",
            CAST("AVG_EXECUTION_TIME" / 1000000 AS DECIMAL(13, 3)) AS "AVG_EXECUTION_TIME_SEC",
            CAST("MAX_EXECUTION_TIME" / 1000000 AS DECIMAL(13, 3)) AS "MAX_EXECUTION_TIME_SEC",
            TO_VARCHAR(ACCESSED_OBJECT_NAMES)
        FROM "E199551"."V_HOST_SQL_PLAN_CACHE"
        where --CAST("AVG_EXECUTION_MEMORY_SIZE"/(1024*1024*1024) AS DECIMAL(13,3)) < 50
            --OR 
            CAST("AVG_EXECUTION_TIME" / 1000000 AS DECIMAL(13, 3)) > 300
    )
GROUP BY APPLICATION_NAME
ORDER BY 4 DESC,
    5 DESC;
------------------
SELECT --"USER_NAME" ,
    APPLICATION_NAME,
    AVG("AVG_EXECUTION_MEMORY_SIZE_GB") AVG_A_EXE_GB,
    MAX("AVG_EXECUTION_MEMORY_SIZE_GB") MAX_A_EXE_GB,
    AVG("MAX_EXECUTION_MEMORY_SIZE_GB") AVG_M_EXE_GB,
    MAX("MAX_EXECUTION_MEMORY_SIZE_GB") MAX_M_EXE_GB,
    AVG(AVG_EXECUTION_TIME_SEC) AVG_A_EXE_TIME_SEC,
    MAX(AVG_EXECUTION_TIME_SEC) MAX_M_EXE_TIME_SEC,
    AVG(MAX_EXECUTION_TIME_SEC) AVG_M_EXE_TIME_SEC,
    MAX(MAX_EXECUTION_TIME_SEC) MAX_M_EXE_TIME_SEC,
    COUNT(*) QUERY_COUNT
FROM (
        SELECT "USER_NAME",
            SESSION_USER_NAME,
            --  "STATEMENT_HASH" STMT_HASH,
            --   TO_VARCHAR(STATEMENT_STRING),
            CAST("SNAPSHOT_ID" AS DATE) SNAP_DATE,
            "APPLICATION_NAME",
            -- "APPLICATION_SOURCE",
            CAST(
                "AVG_EXECUTION_MEMORY_SIZE" /(1024 * 1024) AS DECIMAL(13, 3)
            ) AS "AVG_EXECUTION_MEMORY_SIZE_MB",
            CAST(
                "AVG_EXECUTION_MEMORY_SIZE" /(1024 * 1024 * 1024) AS DECIMAL(13, 3)
            ) AS "AVG_EXECUTION_MEMORY_SIZE_GB",
            CAST(
                "MAX_EXECUTION_MEMORY_SIZE" /(1024 * 1024) AS DECIMAL(13, 3)
            ) AS "MAX_EXECUTION_MEMORY_SIZE_MB",
            CAST(
                "MAX_EXECUTION_MEMORY_SIZE" /(1024 * 1024 * 1024) AS DECIMAL(13, 3)
            ) AS "MAX_EXECUTION_MEMORY_SIZE_GB",
            CAST("AVG_EXECUTION_TIME" / 1000000 AS DECIMAL(13, 3)) AS "AVG_EXECUTION_TIME_SEC",
            CAST("MAX_EXECUTION_TIME" / 1000000 AS DECIMAL(13, 3)) AS "MAX_EXECUTION_TIME_SEC" --    TO_VARCHAR(ACCESSED_OBJECT_NAMES)
        FROM "E199551"."V_HOST_SQL_PLAN_CACHE"
        where CAST(
                "AVG_EXECUTION_MEMORY_SIZE" /(1024 * 1024 * 1024) AS DECIMAL(13, 3)
            ) between.5 and 100 --CAST("AVG_EXECUTION_TIME" / 1000000 AS DECIMAL(13, 3)) > 300
            AND USER_NAME <> 'MART'
            AND APPLICATION_NAME = 'sap.bc.ina.service.v2'
    )
GROUP BY --"USER_NAME"
    -- ,
    APPLICATION_NAME -- ORDER BY 6 desc,3 desc;